/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradl;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public int sumar(int sum1, int sum2){
        return sum1 + sum2; 
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
